"""add_formatting_rules_to_channels

Revision ID: 27a5109c7d8b
Revises: afa736c16866
Create Date: 2026-04-24 10:22:22.588674
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a5109c7d8b'
down_revision: Union[str, None] = 'afa736c16866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('formatting_rules', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'formatting_rules')
    # ### end Alembic commands ###
