"""add_editorial_status_to_project_scores

Revision ID: 46aa0bf4cbd4
Revises: 27a5109c7d8b
Create Date: 2026-04-24 17:06:38.402027
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46aa0bf4cbd4'
down_revision: Union[str, None] = '27a5109c7d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_project_scores', sa.Column('editorial_status', sa.String(length=20), server_default='inbox', nullable=False))
    op.create_index(op.f('ix_material_project_scores_editorial_status'), 'material_project_scores', ['editorial_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_project_scores_editorial_status'), table_name='material_project_scores')
    op.drop_column('material_project_scores', 'editorial_status')
    # ### end Alembic commands ###
