"""Add editorial constraints and MaterialChannelScore

Revision ID: 72fb18c2c165
Revises: ee77840161f9
Create Date: 2026-04-16 18:03:34.178681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fb18c2c165'
down_revision: Union[str, None] = 'ee77840161f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_channel_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('hype_score', sa.Integer(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_channel_scores_channel_id'), 'material_channel_scores', ['channel_id'], unique=False)
    op.create_index(op.f('ix_material_channel_scores_material_id'), 'material_channel_scores', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_channel_scores_tenant_id'), 'material_channel_scores', ['tenant_id'], unique=False)
    op.add_column('channels', sa.Column('editorial_guidelines', sa.String(), server_default='', nullable=False))
    op.add_column('channels', sa.Column('target_audience', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'target_audience')
    op.drop_column('channels', 'editorial_guidelines')
    op.drop_index(op.f('ix_material_channel_scores_tenant_id'), table_name='material_channel_scores')
    op.drop_index(op.f('ix_material_channel_scores_material_id'), table_name='material_channel_scores')
    op.drop_index(op.f('ix_material_channel_scores_channel_id'), table_name='material_channel_scores')
    op.drop_table('material_channel_scores')
    # ### end Alembic commands ###
