"""add_projects_and_channel_adaptations

Revision ID: afa736c16866
Revises: 72fb18c2c165
Create Date: 2026-04-16 21:49:04.569895
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afa736c16866'
down_revision: Union[str, None] = '72fb18c2c165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('topic_guidelines', sa.Text(), server_default='', nullable=False),
    sa.Column('target_audience', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('channel_adaptations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('headline', sa.Text(), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'channel_id', 'language', name='uq_material_channel_lang')
    )
    op.create_index(op.f('ix_channel_adaptations_channel_id'), 'channel_adaptations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_adaptations_material_id'), 'channel_adaptations', ['material_id'], unique=False)
    op.create_index(op.f('ix_channel_adaptations_tenant_id'), 'channel_adaptations', ['tenant_id'], unique=False)
    op.create_table('material_project_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('hype_score', sa.Integer(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'project_id', name='uq_material_project')
    )
    op.create_index(op.f('ix_material_project_scores_material_id'), 'material_project_scores', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_project_scores_project_id'), 'material_project_scores', ['project_id'], unique=False)
    op.create_index(op.f('ix_material_project_scores_tenant_id'), 'material_project_scores', ['tenant_id'], unique=False)
    op.add_column('channels', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('channels', sa.Column('content_format', sa.String(length=50), server_default='short_post', nullable=False))
    op.add_column('channels', sa.Column('tone_of_voice', sa.Text(), server_default='', nullable=False))
    op.add_column('channels', sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), server_default='["ru"]', nullable=False))
    op.add_column('channels', sa.Column('editorial_rules', sa.Text(), server_default='', nullable=False))
    op.create_index(op.f('ix_channels_project_id'), 'channels', ['project_id'], unique=False)
    op.create_foreign_key(None, 'channels', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('channels', 'target_audience')
    op.drop_column('channels', 'editorial_guidelines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('editorial_guidelines', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('channels', sa.Column('target_audience', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_index(op.f('ix_channels_project_id'), table_name='channels')
    op.drop_column('channels', 'editorial_rules')
    op.drop_column('channels', 'languages')
    op.drop_column('channels', 'tone_of_voice')
    op.drop_column('channels', 'content_format')
    op.drop_column('channels', 'project_id')
    op.drop_index(op.f('ix_material_project_scores_tenant_id'), table_name='material_project_scores')
    op.drop_index(op.f('ix_material_project_scores_project_id'), table_name='material_project_scores')
    op.drop_index(op.f('ix_material_project_scores_material_id'), table_name='material_project_scores')
    op.drop_table('material_project_scores')
    op.drop_index(op.f('ix_channel_adaptations_tenant_id'), table_name='channel_adaptations')
    op.drop_index(op.f('ix_channel_adaptations_material_id'), table_name='channel_adaptations')
    op.drop_index(op.f('ix_channel_adaptations_channel_id'), table_name='channel_adaptations')
    op.drop_table('channel_adaptations')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
